- name: "Add NodeJs"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: "Install nodeJs 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 globally"
  npm:
    name: pm2
    global: yes