- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Extract backend files "
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app


- name: "Configure the environment variables"
  shell: |
    export NODE_ENV=production
    export VERSION=1
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_MIGRATIONS_DIR=./migrations
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_MIGRATIONS=./src/migrations/*{.ts,.js}

    export TYPEORM_HOST=$TYPEORM_HOST
    export TYPEORM_PORT=$TYPEORM_PORT
    export TYPEORM_USERNAME=$TYPEORM_USERNAME
    export TYPEORM_PASSWORD=$TYPEORM_PASSWORD
    export TYPEORM_DATABASE=$TYPEORM_DATABASE


- name: "Install global dependencies"
  shell: |
    cd ~/backend-app
    npm i -g @nestjs/cli
    npm i -g reflect-metadata
    npm i -g rxjs
    npm i -g @nestjs/common
    npm i -g @nestjs/core
    npm i -g @nestjs/swagger

- name: "Install NPM Deps"
  shell: |
    cp package.json ..
    cp package-lock.json ..
    cd ~/backend-app
    npm i

- name: "Run node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: "Print Message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure PM2 service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ububtu --hp /home/ubuntu



