- name: "stop pm2"
  shell: |
    pm2 kill

- name: "Install NPM Deps"
  shell: |
    cd ~/backend-app/dist
    npm install
    npm i -g @nestjs/cli
    npm i --save @nestjs/core @nestjs/common rxjs reflect-metadata

- name: "Install global dependencies"
  shell: |
    cd ~/backend-app/dist
    pm2 start main.js
